### PR TITLE
Feat: Added Currency name 

### LINKED ISSUE #1: Add country name along with the currency.
There should be a country name along with the currency name. This will be very useful to the users. 

image

### PR DESCRIPTION
**Pull request by gambhirsharma**
Added Currency name using `Intl` constructor.

### Screen-Shot
image

## Tested
- [x] Firefox
- [x] Chrome

### CODE REVIEW

**Comment by Alkaison** [comment]
Hi @gambhirsharma, it's not able to fetch the country names of all. Should we search some different method for that ?

Screenshot_2023_0603_232827

**Review by Alkaison — CHANGES_REQUESTED** [review]
Only half of the country names are coming, find different method for fetching them.

**Comment by gambhirsharma** [comment]
It's working perfectly fine in my system. 

Tested on: 
OS: MacOS
Brower: Firefox and Chrome

## ScreenShot
IMG20230603235045

** It's not displaying the name of 7 currencies bcoz they no longer exist, they are replaced by new currencies.

**Comment by Alkaison** [comment]
You are right @gambhirsharma, it is showing the country names on browser but only on laptop, PC. I tried the same on mobile it's not showing. probably would have to add this data to the array and fetch from there for compatibility on both devices. Approving this PR as this does work as expected.

**Review by Alkaison — APPROVED** [review]

**Pull request merged**
